// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetSourcesData, GetSourcesErrors, GetSourcesResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class SourcesService {
    public static getSources<ThrowOnError extends boolean = false>(options?: Options<GetSourcesData, ThrowOnError>): RequestResult<GetSourcesResponses, GetSourcesErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetSourcesResponses, GetSourcesErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/log-explorer/api/v1/sources',
            ...options
        });
    }
}
