// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44372' | (string & {});
};

export type AndNode = {
    kind: 'and';
    children: Array<AndNode | OrNode | NotNode | ConditionNode | TextNode>;
};

export type ConditionNode = {
    kind: 'condition';
    field: string;
    op: FilterOperator;
    value?: unknown;
    caseInsensitive?: boolean;
};

export type Facet = {
    field: string;
    presenceRatio: number;
    topValues: Array<FacetValue>;
};

export type FacetResult = {
    facets: Array<Facet>;
    approximate: boolean;
    scannedRange: ResolvedRange;
};

export type FacetValue = {
    value: unknown;
    count: number;
};

export type FacetsRequest = {
    query: LogQuery;
    fields: Array<string>;
    top: number;
};

export type FieldInfo = {
    path: string;
    kind: string;
    presenceRatio: number;
};

export type FilterOperator = 'equals' | 'notEquals' | 'contains' | 'startsWith' | 'endsWith' | 'greaterThan' | 'greaterOrEqual' | 'lessThan' | 'lessOrEqual' | 'in' | 'exists' | 'notExists' | 'matches';

export type HistogramBucket = {
    start: string;
    countsBySeverityShortName: {
        [key: string]: number;
    };
};

export type HistogramRequest = {
    query: LogQuery;
    targetBuckets: number;
};

export type HistogramResult = {
    range: ResolvedRange;
    bucketSize: string;
    buckets: Array<HistogramBucket>;
    approximate: boolean;
};

export type LogException = {
    type?: string | null;
    message?: string | null;
    stackTrace?: string | null;
};

export type LogPage = {
    records: Array<LogRecord>;
    nextCursor?: string | null;
    range: ResolvedRange;
    totalCount?: number | null;
    totalIsLowerBound: boolean;
    warnings: Array<string>;
};

export type LogQuery = {
    range: TimeRange;
    levels?: Array<string> | null;
    filter?: AndNode | OrNode | NotNode | ConditionNode | TextNode | null;
    nativeQuery?: string | null;
    take: number;
    cursor?: string | null;
    sort: SortDirection;
};

export type LogRecord = {
    id: string;
    timestamp: string;
    severityNumber: number;
    severityText?: string | null;
    body?: string | null;
    messageTemplate?: string | null;
    templateHash?: string | null;
    traceId?: string | null;
    spanId?: string | null;
    scope?: string | null;
    exception?: LogException | null;
    attributes: {
        [key: string]: unknown;
    };
    resource: {
        [key: string]: unknown;
    };
    sourceAlias: string;
};

export type NotNode = {
    kind: 'not';
    child: AndNode | OrNode | NotNode | ConditionNode | TextNode;
};

export type OrNode = {
    kind: 'or';
    children: Array<AndNode | OrNode | NotNode | ConditionNode | TextNode>;
};

export type ParseFallback = {
    code: string;
    message: string;
};

export type ParseRequest = {
    input?: string | null;
};

export type ParseResult = {
    chips: Array<AndNode | OrNode | NotNode | ConditionNode | TextNode>;
    levels?: Array<string> | null;
    fallback?: ParseFallback | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown;
};

export type ResolvedRange = {
    from: string;
    to: string;
};

export type SettingsResponseModel = {
    hideCoreLogViewer: boolean;
    defaultSource: string;
    defaultTimeRange: string;
    pinnedFacets: Array<string>;
};

export type SortDirection = 'descending' | 'ascending';

export type SourceCapabilitiesResponseModel = {
    features: Array<string>;
    operators: Array<string>;
    nativeLanguage?: string | null;
    maxRangeSeconds?: number | null;
    maxPageSize: number;
};

export type SourceResponseModel = {
    alias: string;
    displayName: string;
    type: string;
    sensitive: boolean;
    capabilities: SourceCapabilitiesResponseModel;
};

export type TextNode = {
    kind: 'text';
    text: string;
    phrase?: boolean;
};

export type TimeRange = {
    from?: string | null;
    to?: string | null;
    relative?: string | null;
};

export type GetFacetsData = {
    body?: FacetsRequest;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/log-explorer/api/v1/sources/{alias}/facets';
};

export type GetFacetsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetFacetsError = GetFacetsErrors[keyof GetFacetsErrors];

export type GetFacetsResponses = {
    /**
     * OK
     */
    200: FacetResult;
};

export type GetFacetsResponse = GetFacetsResponses[keyof GetFacetsResponses];

export type GetFieldsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        from?: string;
        to?: string;
        relative?: string;
    };
    url: '/umbraco/log-explorer/api/v1/sources/{alias}/fields';
};

export type GetFieldsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetFieldsError = GetFieldsErrors[keyof GetFieldsErrors];

export type GetFieldsResponses = {
    /**
     * OK
     */
    200: Array<FieldInfo>;
};

export type GetFieldsResponse = GetFieldsResponses[keyof GetFieldsResponses];

export type GetHistogramData = {
    body?: HistogramRequest;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/log-explorer/api/v1/sources/{alias}/histogram';
};

export type GetHistogramErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetHistogramError = GetHistogramErrors[keyof GetHistogramErrors];

export type GetHistogramResponses = {
    /**
     * OK
     */
    200: HistogramResult;
};

export type GetHistogramResponse = GetHistogramResponses[keyof GetHistogramResponses];

export type ParseData = {
    body?: ParseRequest;
    path?: never;
    query?: never;
    url: '/umbraco/log-explorer/api/v1/parse';
};

export type ParseErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ParseError = ParseErrors[keyof ParseErrors];

export type ParseResponses = {
    /**
     * OK
     */
    200: ParseResult;
};

export type ParseResponse = ParseResponses[keyof ParseResponses];

export type SearchData = {
    body?: LogQuery;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/log-explorer/api/v1/sources/{alias}/search';
};

export type SearchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    /**
     * OK
     */
    200: LogPage;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/log-explorer/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/log-explorer/api/v1/sources';
};

export type GetSourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSourcesResponses = {
    /**
     * OK
     */
    200: Array<SourceResponseModel>;
};

export type GetSourcesResponse = GetSourcesResponses[keyof GetSourcesResponses];
