// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44370' | (string & {});
};

export type SettingsResponseModel = {
    hideCoreLogViewer: boolean;
    defaultSource: string;
    defaultTimeRange: string;
};

export type SourceCapabilitiesResponseModel = {
    features: Array<string>;
    operators: Array<string>;
    nativeLanguage?: string | null;
    maxRangeSeconds?: number | null;
    maxPageSize: number;
};

export type SourceResponseModel = {
    alias: string;
    displayName: string;
    type: string;
    sensitive: boolean;
    capabilities: SourceCapabilitiesResponseModel;
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/log-explorer/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/log-explorer/api/v1/sources';
};

export type GetSourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSourcesResponses = {
    /**
     * OK
     */
    200: Array<SourceResponseModel>;
};

export type GetSourcesResponse = GetSourcesResponses[keyof GetSourcesResponses];
